import { useEffect, useRef, useState } from "react";
import { Loader2, Sparkles } from "lucide-react";
import { useTranslation } from "react-i18next";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import {
  checkpoints as dbCheckpoints,
  conversations as dbConversations,
  messages as dbMessages,
  type ApiCredential,
  type Checkpoint,
  type Model,
  type ProjectStage,
} from "@/lib/db";
import { getApiKey } from "@/lib/keystore";
import { generateCheckpointDraft } from "@/lib/llm/checkpoint-generator";
import { getLanguageModel } from "@/lib/llm/provider-factory";
import { formatTime, roleLabel } from "./project-detail-utils";

const CHECKPOINT_FIELD_KEYS = [
  "goal",
  "completedSummary",
  "currentContext",
  "decisions",
  "failedAttempts",
  "blockers",
  "nextSteps",
  "doNotRepeat",
  "acceptanceCriteria",
] as const;

type CheckpointFieldKey = (typeof CHECKPOINT_FIELD_KEYS)[number];
type CheckpointDraftState = Record<CheckpointFieldKey, string>;

const EMPTY_DRAFT: CheckpointDraftState = {
  goal: "",
  completedSummary: "",
  currentContext: "",
  decisions: "",
  failedAttempts: "",
  blockers: "",
  nextSteps: "",
  doNotRepeat: "",
  acceptanceCriteria: "",
};

export function CreateCheckpointDialog({
  open,
  onOpenChange,
  projectId,
  stages,
  models,
  credentials,
  onCreated,
}: {
  open: boolean;
  onOpenChange: (v: boolean) => void;
  projectId: string;
  stages: ProjectStage[];
  models: Model[];
  credentials: ApiCredential[];
  onCreated: () => void;
}) {
  const { t } = useTranslation();
  const [title, setTitle] = useState("");
  const [fields, setFields] = useState<CheckpointDraftState>(EMPTY_DRAFT);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const stagesWithConversation = stages.filter((s) => s.status !== "pending");
  const [selectedStageId, setSelectedStageId] = useState<string>("");
  const [generating, setGenerating] = useState(false);
  const [generateError, setGenerateError] = useState<string | null>(null);
  const autoGeneratedForRef = useRef<string | null>(null);

  useEffect(() => {
    if (!open) {
      autoGeneratedForRef.current = null;
      return;
    }
    if (!selectedStageId && stagesWithConversation.length > 0) {
      setSelectedStageId(stagesWithConversation[stagesWithConversation.length - 1]!.id);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, stages]);

  useEffect(() => {
    if (open && selectedStageId && autoGeneratedForRef.current !== selectedStageId) {
      autoGeneratedForRef.current = selectedStageId;
      void handleGenerate();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, selectedStageId]);

  function reset() {
    setTitle("");
    setFields(EMPTY_DRAFT);
    setError(null);
    setSelectedStageId("");
    setGenerateError(null);
    autoGeneratedForRef.current = null;
  }

  async function handleGenerate() {
    const stage = stages.find((s) => s.id === selectedStageId);
    if (!stage) {
      setGenerateError(t("projectDetail.createCheckpoint.selectStageFirst"));
      return;
    }
    const model = models.find((m) => m.id === stage.modelId);
    const credential = model && credentials.find((c) => c.providerId === model.providerId);
    if (!model || !credential || !model.provider?.type) {
      setGenerateError(t("projectDetail.createCheckpoint.noModelOrCred"));
      return;
    }

    setGenerating(true);
    setGenerateError(null);
    try {
      const convs = await dbConversations.list();
      const convTitle = `${stage.projectId}:${stage.id}`;
      const conv = convs.find((c) => c.projectId === stage.projectId && c.title === convTitle);
      const history = conv ? await dbMessages.listByConversation(conv.id) : [];

      const apiKey = await getApiKey(credential.id);
      if (!apiKey) {
        setGenerateError(t("projectDetail.createCheckpoint.apiKeyMissing"));
        return;
      }

      const languageModel = getLanguageModel(
        model.provider.type,
        model.name,
        apiKey,
        credential.baseUrl,
      );
      const draft = await generateCheckpointDraft(
        languageModel,
        history.map((m) => ({ role: m.role as "user" | "assistant" | "system", content: m.content })),
      );

      setTitle(draft.title);
      setFields({
        goal: draft.goal,
        completedSummary: draft.completedSummary,
        currentContext: draft.currentContext,
        decisions: draft.decisions,
        failedAttempts: draft.failedAttempts,
        blockers: draft.blockers,
        nextSteps: draft.nextSteps,
        doNotRepeat: draft.doNotRepeat,
        acceptanceCriteria: draft.acceptanceCriteria,
      });
    } catch (err) {
      setGenerateError(err instanceof Error ? err.message : t("projectDetail.createCheckpoint.generateFailed"));
    } finally {
      setGenerating(false);
    }
  }

  async function handleSave() {
    if (!title.trim()) {
      setError(t("projectDetail.createCheckpoint.titleRequired"));
      return;
    }
    setSaving(true);
    setError(null);
    try {
      await dbCheckpoints.create({
        projectId,
        title: title.trim(),
        goal: fields.goal.trim() || null,
        completedSummary: fields.completedSummary.trim() || null,
        currentContext: fields.currentContext.trim() || null,
        decisions: fields.decisions.trim() || null,
        failedAttempts: fields.failedAttempts.trim() || null,
        blockers: fields.blockers.trim() || null,
        nextSteps: fields.nextSteps.trim() || null,
        doNotRepeat: fields.doNotRepeat.trim() || null,
        acceptanceCriteria: fields.acceptanceCriteria.trim() || null,
      });
      reset();
      onOpenChange(false);
      onCreated();
    } catch (err) {
      setError(err instanceof Error ? err.message : t("projectDetail.createCheckpoint.saveFailed"));
    } finally {
      setSaving(false);
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto glass border-white/10 rounded-[2rem]">
        <DialogHeader>
          <DialogTitle className="font-black tracking-tight">{t("projectDetail.createCheckpoint.title")}</DialogTitle>
        </DialogHeader>
        <div className="space-y-3 text-sm">
          {error && (
            <Alert variant="destructive" className="py-2">
              <AlertDescription className="text-xs">{error}</AlertDescription>
            </Alert>
          )}
          {stagesWithConversation.length > 0 && (
            <div className="flex items-end gap-2 bg-muted/30 rounded-xl p-2.5">
              <div className="flex-1 space-y-1.5">
                <Label htmlFor="cp-stage">{t("projectDetail.createCheckpoint.selectStage")}</Label>
                <Select value={selectedStageId} onValueChange={setSelectedStageId}>
                  <SelectTrigger id="cp-stage">
                    <SelectValue placeholder={t("projectDetail.createCheckpoint.selectStagePlaceholder")} />
                  </SelectTrigger>
                  <SelectContent>
                    {stagesWithConversation.map((s) => (
                      <SelectItem key={s.id} value={s.id}>
                        {roleLabel(s.workRole, t) ?? s.workRole}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <Button
                type="button"
                size="sm"
                variant="secondary"
                onClick={() => void handleGenerate()}
                disabled={generating || !selectedStageId}
              >
                {generating ? (
                  <Loader2 className="w-3.5 h-3.5 mr-1 animate-spin" />
                ) : (
                  <Sparkles className="w-3.5 h-3.5 mr-1" />
                )}
                {generating ? t("projectDetail.createCheckpoint.generating") : t("projectDetail.createCheckpoint.regenerate")}
              </Button>
            </div>
          )}
          {generating && !generateError && (
            <p className="text-xs text-muted-foreground flex items-center gap-1.5">
              <Loader2 className="w-3 h-3 animate-spin" /> {t("projectDetail.createCheckpoint.generatingHint")}
            </p>
          )}
          {generateError && (
            <Alert variant="destructive" className="py-2">
              <AlertDescription className="text-xs">{generateError}</AlertDescription>
            </Alert>
          )}
          <div className="space-y-1.5">
            <Label htmlFor="cp-title">{t("projectDetail.createCheckpoint.titleLabel")}</Label>
            <Input
              id="cp-title"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder={t("projectDetail.createCheckpoint.titlePlaceholder")}
            />
          </div>
          {CHECKPOINT_FIELD_KEYS.map((key) => (
            <div key={key} className="space-y-1.5">
              <Label htmlFor={`cp-${key}`}>{t(`projectDetail.fields.${key}`)}</Label>
              <Textarea
                id={`cp-${key}`}
                value={fields[key]}
                onChange={(e) => setFields((prev) => ({ ...prev, [key]: e.target.value }))}
                placeholder={t(`projectDetail.placeholders.${key}`)}
                rows={2}
              />
            </div>
          ))}
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)} disabled={saving}>
            {t("common.cancel")}
          </Button>
          <Button onClick={() => void handleSave()} disabled={saving || !title.trim()}>
            {saving ? t("projectDetail.createCheckpoint.saving") : t("projectDetail.createCheckpoint.create")}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

export function CheckpointDetailDialog({
  checkpoint,
  open,
  onOpenChange,
}: {
  checkpoint: Checkpoint | null;
  open: boolean;
  onOpenChange: (v: boolean) => void;
}) {
  const { t } = useTranslation();
  if (!checkpoint) return null;
  const fields: Array<[string, string]> = [
    ["goal", checkpoint.goal ?? ""],
    ["completedSummary", checkpoint.completedSummary ?? ""],
    ["currentContext", checkpoint.currentContext ?? ""],
    ["decisions", checkpoint.decisions ?? ""],
    ["failedAttempts", checkpoint.failedAttempts ?? ""],
    ["blockers", checkpoint.blockers ?? ""],
    ["nextSteps", checkpoint.nextSteps ?? ""],
    ["doNotRepeat", checkpoint.doNotRepeat ?? ""],
    ["acceptanceCriteria", checkpoint.acceptanceCriteria ?? ""],
  ];
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto glass border-white/10 rounded-[2rem]">
        <DialogHeader>
          <DialogTitle className="font-black tracking-tight">{checkpoint.title}</DialogTitle>
        </DialogHeader>
        <div className="text-xs text-muted-foreground">
          {t("projectDetail.checkpointDetail.createdAt", { time: formatTime(checkpoint.createdAt) })}
        </div>
        <div className="space-y-3 text-sm">
          {fields.map(([label, value]) => (
            <div key={label} className="space-y-1">
              <div className="font-medium">{t(`projectDetail.fields.${label}`)}</div>
              <div className="text-muted-foreground whitespace-pre-wrap">
                {value || <span className="italic">{t("projectDetail.checkpointDetail.empty")}</span>}
              </div>
            </div>
          ))}
        </div>
      </DialogContent>
    </Dialog>
  );
}
